spring:
  # ===============================
  #           datasource          #
  # ===============================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/golkar
    username: root
    password:

  # ===============================
  # = Redis configurations
  # ===============================ß
#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600000
#      cache-null-values: true
  # ===============================
  # = Logging configurations
  # ===============================
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
    file: "%d %-5level [%thread] %logger{0} : %msg%n"